### ISSUE TITLE
How does the argument system work ? 

### ISSUE THREAD

**Issue by Coretool** [piranna/coreutils.js#4]
I am finishing the mkdir utility and saw your arg system which I don't quite understand -.- Can you give me a brief explenation of it ?

**Comment by piranna** [comment]
Are you talking about [these lines](https://github.com/piranna/coreutils.js/blob/1ec5c2c20e429827f43cc6faf8d0d02d60b3ae2d/lib/common.js#L14-L20)? It's a little bit of Javascript magic :-P The idea is that you could be able to call to the functions with a parameters object and use it directly as the function parameters, or as an array or by using positional arguments, in that case using [minimist](https://github.com/substack/minimist) as usual to create the parameters object.

Don't worry if you don't fully understand how it works, I can be able to review it later :-)

**Comment by Coretool** [comment]
Thanks! I think I got it =)

**Comment by piranna** [comment]
:+1:
